services:
  auth:
    build: 
      context: ./todo-auth
      dockerfile: Dockerfile

    env_file:
      - ./todo-auth/.development.env

    volumes:
      - ./todo-auth/src:/app/src

    ports:
      - 5001:5001
    
    command: npm run start:dev

    depends_on:
      - postgres
      - rabbitmq

  main:
    build: 
      context: ./todo-server
      dockerfile: Dockerfile

    env_file:
      - ./todo-server/.development.env

    volumes:
      - ./todo-server/src:/app/src

    ports:
      - 5000:5000
      
    command: npm run start:dev

    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres

    image: postgres:17

    environment:
      POSTGRES_DB: "todo-database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      
    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresgl/data

    restart: always
  
  rabbitmq:

    container_name: rabbitmq

    image: rabbitmq:management

    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata: